### ISSUE TITLE
Terraform Boundary Provider Error ehile executing terraform plan

### ISSUE THREAD

**Issue by Admir-Hadzic-MOP** [hashicorp/boundary#1163]
**Describe the bug**
While trying to configure Boundary using terraform I got "Error: error calling read scope: error performing client request during Read call: context deadline exceeded" and after that Terraform crashed.

**To Reproduce**
1. Create a boundary provider pointing to your Controller or ELB
2. Run Terraform plan

**Expected behavior**
I wanted to start configuring Boundary using boundary provider for Terraform. 
provider "boundary" {
  addr = "http://Controller_IP:9200"
  auth_method_id   = "ampw_biNG219i4V"  
  password_auth_method_login_name = "admin"
  password_auth_method_password   = "**************"
  recovery_kms_hcl = <<EOT
    kms "awskms" {
      purpose    = "recovery"
      key_id     = "global_root"
      kms_key_id = "${var.kms_recovery_key_id}"
    }
  EOT
}

**Additional context**
crash.log
panic: runtime error: invalid memory address or nil pointer dereference
2021-04-23T12:53:06.013Z [DEBUG] plugin.terraform-provider-boundary_v1.0.1_x5: [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x111115b]
2021-04-23T12:53:06.013Z [DEBUG] plugin.terraform-provider-boundary_v1.0.1_x5:
2021-04-23T12:53:06.013Z [DEBUG] plugin.terraform-provider-boundary_v1.0.1_x5: goroutine 85 [running]:
2021-04-23T12:53:06.013Z [DEBUG] plugin.terraform-provider-boundary_v1.0.1_x5: github.com/hashicorp/terraform-provider-boundary/internal/provider.resourceGroupRead(0x162f680, 0xc000140480, 0xc00011dc80, 0x11ab440, 0xc0003cce00, 0xc000660800, 0xc0005358b0, 0x40e1b8)
2021-04-23T12:53:06.013Z [DEBUG] plugin.terraform-provider-boundary_v1.0.1_x5:  /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/hashicorp/terraform-provider-boundary/internal/provider/resource_group.go:131 +0x27b
2021-04-23T12:53:06.014Z [DEBUG] plugin.terraform-provider-boundary_v1.0.1_x5: github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0xc0004bd8c0, 0x162f600, 0xc000514500, 0xc00011dc80, 0x11ab440, 0xc0003cce00, 0x0, 0x0, 0x0)
2021-04-23T12:53:06.014Z [DEBUG] plugin.terraform-provider-boundary_v1.0.1_x5:  /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.0.5-0.20201016174159-3a1c6c51f716/helper/schema/resource.go:287 +0x1ea
2021-04-23T12:53:06.014Z [DEBUG] plugin.terraform-provider-boundary_v1.0.1_x5: github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc0004bd8c0, 0x162f600, 0xc000514500, 0xc0000d30a0, 0x11ab440, 0xc0003cce00, 0xc0000b2d00, 0x0, 0x0, 0x0)
2021-04-23T12:53:06.014Z [DEBUG] plugin.terraform-provider-boundary_v1.0.1_x5:  /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.0.5-0.20201016174159-3a1c6c51f716/helper/schema/resource.go:554 +0x1cb
2021-04-23T12:53:06.014Z [DEBUG] plugin.terraform-provider-boundary_v1.0.1_x5: github.com/hashicorp/terraform-plugin-sdk/v2/internal/helper/plugin.(*GRPCProviderServer).ReadResource(0xc0003cd020, 0x162f600, 0xc000514500, 0xc000140180, 0xc0003cd020, 0xc0003cd030, 0x148fe38)
2021-04-23T12:53:06.014Z [DEBUG] plugin.terraform-provider-boundary_v1.0.1_x5:  /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.0.5-0.20201016174159-3a1c6c51f716/internal/helper/plugin/grpc_provider.go:572 +0x43b
2021-04-23T12:53:06.014Z [DEBUG] plugin.terraform-provider-boundary_v1.0.1_x5: github.com/hashicorp/terraform-plugin-sdk/v2/internal/tfplugin5._Provider_ReadResource_Handler.func1(0x162f600, 0xc000514500, 0x138ba80, 0xc000140180, 0xc000514500, 0x12aaf60, 0xc000140101, 0xc000543b80)
2021-04-23T12:53:06.014Z [DEBUG] plugin.terraform-provider-boundary_v1.0.1_x5:  /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.0.5-0.20201016174159-3a1c6c51f716/internal/tfplugin5/tfplugin5.pb.go:3276 +0x89
2021-04-23T12:53:06.014Z [DEBUG] plugin.terraform-provider-boundary_v1.0.1_x5: github.com/hashicorp/terraform-plugin-sdk/v2/plugin.Serve.func3.1(0x162f6c0, 0xc000485290, 0x138ba80, 0xc000140180, 0xc000543b60, 0xc000543b80, 0xc0004ecba0, 0x49b926, 0x1352ce0, 0xc000485290)
2021-04-23T12:53:06.014Z [DEBUG] plugin.terraform-provider-boundary_v1.0.1_x5:  /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.0.5-0.20201016174159-3a1c6c51f716/plugin/serve.go:76 +0x87
2021-04-23T12:53:06.014Z [DEBUG] plugin.terraform-provider-boundary_v1.0.1_x5: github.com/hashicorp/terraform-plugin-sdk/v2/internal/tfplugin5._Provider_ReadResource_Handler(0x13bc760, 0xc0003cd020, 0x162f6c0, 0xc000485290, 0xc000140120, 0xc0005b8040, 0x162f6c0, 0xc000485290, 0xc000530500, 0x98)
2021-04-23T12:53:06.014Z [DEBUG] plugin.terraform-provider-boundary_v1.0.1_x5:  /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.0.5-0.20201016174159-3a1c6c51f716/internal/tfplugin5/tfplugin5.pb.go:3278 +0x150
2021-04-23T12:53:06.014Z [DEBUG] plugin.terraform-provider-boundary_v1.0.1_x5: google.golang.org/grpc.(*Server).processUnaryRPC(0xc000094700, 0x163e4c0, 0xc000001500, 0xc0000d7f00, 0xc0003e1aa0, 0x1e9c4d0, 0x0, 0x0, 0x0)
2021-04-23T12:53:06.014Z [DEBUG] plugin.terraform-provider-boundary_v1.0.1_x5:  /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.34.0/server.go:1210 +0x522
2021-04-23T12:53:06.014Z [DEBUG] plugin.terraform-provider-boundary_v1.0.1_x5: google.golang.org/grpc.(*Server).handleStream(0xc000094700, 0x163e4c0, 0xc000001500, 0xc0000d7f00, 0x0)
2021-04-23T12:53:06.014Z [DEBUG] plugin.terraform-provider-boundary_v1.0.1_x5:  /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.34.0/server.go:1533 +0xd05
2021-04-23T12:53:06.014Z [DEBUG] plugin.terraform-provider-boundary_v1.0.1_x5: google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc000040240, 0xc000094700, 0x163e4c0, 0xc000001500, 0xc0000d7f00)
2021-04-23T12:53:06.014Z [DEBUG] plugin.terraform-provider-boundary_v1.0.1_x5:  /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.34.0/server.go:871 +0xa5
2021-04-23T12:53:06.014Z [DEBUG] plugin.terraform-provider-boundary_v1.0.1_x5: created by google.golang.org/grpc.(*Server).serveStreams.func1
2021-04-23T12:53:06.014Z [DEBUG] plugin.terraform-provider-boundary_v1.0.1_x5:  /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.34.0/server.go:869 +0x1fd
2021/04/23 12:53:06 [TRACE] vertex "module.boundary.module.boundary_management.boundary_group.dealings_group (orphan)": visit complete
2021-04-23T12:53:06.015Z [DEBUG] plugin: plugin process exited: path=.terraform/providers/registry.terraform.io/hashicorp/boundary/1.0.1/linux_amd64/terraform-provider-boundary_v1.0.1_x5 pid=1631 error="exit status 2"
2021/04/23 12:53:06 [TRACE] vertex "module.boundary.module.boundary_management.boundary_scope.devops_team (orphan)": visit complete
2021/04/23 12:53:06 [TRACE] vertex "module.boundary.module.boundary_management.boundary_auth_method.password (orphan)": visit complete
2021/04/23 12:53:06 [TRACE] vertex "module.boundary.module.boundary_management.boundary_account.devops_user_acct[\"zijad.purkovic\"] (orphan)": visit complete
2021-04-23T12:53:06.015Z [WARN]  plugin.stdio: received EOF, stopping recv loop: err="rpc error: code = Unavailable desc = transport is closing"
2021/04/23 12:53:06 [TRACE] vertex "module.boundary.module.boundary_management.boundary_scope.sxdev": visit complete
2021/04/23 12:53:06 [TRACE] vertex "module.boundary.module.boundary_management.boundary_scope.sxdev": dynamic subgraph encountered errors
2021/04/23 12:53:06 [TRACE] vertex "module.boundary.module.boundary_management.boundary_scope.sxdev": visit complete
2021/04/23 12:53:06 [TRACE] vertex "module.boundary.module.boundary_management.boundary_scope.sxdev (expand)": dynamic subgraph encountered errors
2021/04/23 12:53:06 [TRACE] vertex "module.boundary.module.boundary_management.boundary_scope.sxdev (expand)": visit complete
2021/04/23 12:53:06 [TRACE] dag/walk: upstream of "module.boundary.module.boundary_management.provider[\"registry.terraform.io/hashicorp/boundary\"] (close)" errored, so skipping
2021/04/23 12:53:06 [TRACE] dag/walk: upstream of "module.boundary.module.boundary_management (close)" errored, so skipping
2021/04/23 12:53:06 [TRACE] dag/walk: upstream of "module.boundary (close)" errored, so skipping
2021/04/23 12:53:06 [TRACE] dag/walk: upstream of "meta.count-boundary (EachMode fixup)" errored, so skipping
2021/04/23 12:53:06 [TRACE] dag/walk: upstream of "root" errored, so skipping
2021/04/23 12:53:06 [INFO] backend/local: plan operation completed
2021-04-23T12:53:06.016Z [DEBUG] plugin: plugin exited

**Comment by Admir-Hadzic-MOP** [comment]
I still haven't solved terraform configuration with terraform.
Every time I get this error:
module.boundary.module.boundary_management.boundary_scope.sxdev: Still creating... [1m0s elapsed]
Error: error calling read scope: error performing client request during Read call: context deadline exceeded

This is the the terraform config file for the scopes:

######################
# Global SXDEV Scope #
#####################

resource "boundary_scope" "sxdev" {
  global_scope = true
  name         = "SXDEV"
  description  = "Global Scope for SXDEV"
  scope_id     = "global"
}



##############################
# MetaTrader Windows Project #
##############################

resource "boundary_scope" "metatrader_windows" {
  name        = "metatrader-windows"
  description = "MetaTrader Windows"
  scope_id    = boundary_scope.sxdev.id
}



####################
# Active Directory Project #
####################

resource "boundary_scope" "active_directory_domain_services_project" {
  name        = "active-directory-domain-services-project"
  description = "Active Directory Domain Services Project"
  scope_id    = boundary_scope.sxdev.id
}

# Active Directory Windows Project #
####################################
resource "boundary_scope" "active_directory_windows" {
  name        = "active-directory-windows"
  description = "Active Directory Windows"
  scope_id    = boundary_scope.active_directory_domain_services_project.id
}

# Active Directory Linux Project #
##################################
resource "boundary_scope" "active_directory_linux" {
  name        = "active-directory-linux"
  description = "Active Directory Linux"
  scope_id    = boundary_scope.active_directory_domain_services_project.id
}

**Comment by malnick** [comment]
Thanks for opening this, can you confirm is your provider configuration you copied here is using `addr = "http://Controller_IP:9200"` or did you redact the IP for privacy in this issue? If you are using an actual IP or resolvable domain name, can you also verify that you can reach that controller and port combo using telnet or a similar tool from the host where terraform is running?

**Comment by malnick** [comment]
Great! Will close this out.
