### ISSUE TITLE
If not all options are set in the configuration file, then we will get the following error like panic

### ISSUE THREAD

**Issue by skolenkin** [hashicorp/boundary#819]
If not all options are set in the configuration file, then we will get the following error like panic: runtime error: invalid memory address or nil pointer dereference
If we set not all parameters in the boundary configuration file, then we will get the following error:
```
sudo boundary database init -config /etc/boundary/boundary.hcl
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x126af3f]
goroutine 1 [running]:
github.com/hashicorp/boundary/internal/cmd/commands/database.(*InitCommand).Run(0xc0005401e0, 0xc00010c030, 0x2, 0x2, 0x0)
	/go/internal/cmd/commands/database/init.go:208 +0x2ff
github.com/mitchellh/cli.(*CLI).Run(0xc0003683c0, 0xc0003683c0, 0xc00052aa00, 0xc000074260)
	/root/go/pkg/mod/github.com/mitchellh/cli@v1.1.2/cli.go:262 +0x1cf
github.com/hashicorp/boundary/internal/cmd.RunCustom(0xc00010c010, 0x4, 0x4, 0xc000841e60, 0xc000080058)
	/go/internal/cmd/main.go:186 +0x846
github.com/hashicorp/boundary/internal/cmd.Run(...)
	/go/internal/cmd/main.go:92
main.main()
	/go/cmd/boundary/main.go:13 +0xda
```

```
boundary version
Version information:
  Git Revision:        d8020842ae8b6c742b94538baada313d7eb52809
  Version Number:      0.1.2
```

Expected result: error message with a small clarification
Current result: go traceback

Could you please add in the command boundary “check config” option? Also, it would be better to add a sample boundary config file in documentation.

**Comment by malnick** [comment]
Thanks for raising this @skolenkin - can you add the configuration file you used in running this command (with any sensitive values redacted)?

**Comment by skolenkin** [comment]
/etc/boundary/boundary2.hcl
```
#controller {
#  name = "coe-controller-1"
#  description = "A controller for a COE!"

#  database {
    #url = "env://BOUNDARY_POSTGRES_URL"
#    url = "postgresql://postgres:PASSWORD@127.0.0.1:5432/boundary?sslmode=disable"
#  }
#}

disable_mlock = true
listener "tcp" {
  address = "0.0.0.0"
  #address = "127.0.0.1"
  purpose = "api"
  tls_disable = true
}

listener "tcp" {
  address = "0.0.0.0"
  #address = "127.0.0.1"
  purpose = "cluster"
  tls_disable   = true
}

listener "tcp" {
  address       = "0.0.0.0"
  #address       = "127.0.0.1"
  purpose       = "proxy"
  tls_disable   = true
}

```
```
boundary database init -config /etc/boundary/boundary2.hcl
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x126af3f]

goroutine 1 [running]:
github.com/hashicorp/boundary/internal/cmd/commands/database.(*InitCommand).Run(0xc000420780, 0xc00003a080, 0x2, 0x2, 0x0)
        /go/internal/cmd/commands/database/init.go:208 +0x2ff
github.com/mitchellh/cli.(*CLI).Run(0xc0000ba3c0, 0xc0000ba3c0, 0xc00036a060, 0xc00027c8c0)
        /root/go/pkg/mod/github.com/mitchellh/cli@v1.1.2/cli.go:262 +0x1cf
github.com/hashicorp/boundary/internal/cmd.RunCustom(0xc00003a060, 0x4, 0x4, 0xc000579e60, 0xc00008a058)
        /go/internal/cmd/main.go:186 +0x846
github.com/hashicorp/boundary/internal/cmd.Run(...)
        /go/internal/cmd/main.go:92
main.main()
        /go/cmd/boundary/main.go:13 +0xda
```

**Comment by malnick** [comment]
Thank you! Assigning to @louisruch to repro and patch.
