### ISSUE TITLE
boundary fails to execute

### ISSUE THREAD

**Issue by frntn** [hashicorp/boundary#830]
**Describe the bug**

On a fresh ubuntu 20.04 install on top of a fresh windows 10 install, using WSL 2 I have the following error when trying to execute `boundary` binary
```
$ boundary
panic: runtime error: slice bounds out of range [308:282]

goroutine 1 [running]:
github.com/godbus/dbus.getSessionBusPlatformAddress(0x1805baa, 0x18, 0x0, 0x0)
        /root/go/pkg/mod/github.com/godbus/dbus@v4.1.0+incompatible/conn_other.go:30 +0x295
github.com/godbus/dbus.getSessionBusAddress(0x0, 0x0, 0x0, 0x0)
        /root/go/pkg/mod/github.com/godbus/dbus@v4.1.0+incompatible/conn.go:96 +0xf8
github.com/godbus/dbus.SessionBusPrivate(0x0, 0x168b740, 0x263f390)
        /root/go/pkg/mod/github.com/godbus/dbus@v4.1.0+incompatible/conn.go:101 +0x25
github.com/godbus/dbus.SessionBus(0x0, 0x0, 0x0)
        /root/go/pkg/mod/github.com/godbus/dbus@v4.1.0+incompatible/conn.go:73 +0xb5
github.com/99designs/keyring.init.1()
        /root/go/pkg/mod/github.com/99designs/keyring@v1.1.6/kwallet.go:24 +0x51
```

**To Reproduce**
```
$ curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
$ sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
$ sudo apt-get update && sudo apt-get install boundary
$ boundary
```
**Expected behavior**

```
$ boundary
Usage: boundary <command> [args]

Commands:
    accounts           Manage Boundary accounts
    auth-methods       Manage Boundary auth-methods
    auth-tokens        Manage Boundary auth-tokens
    authenticate       Authenticate the Boundary command-line client
    config             Manage resources related to Boundary's local configuration
    connect            Authorize a session against a target and launch a proxied connection
    database           Manage Boundary's database
    dev                Start a Boundary dev environment
    groups             Manage Boundary groups
    host-catalogs      Manage Boundary host-catalogs
    host-sets          Manage Boundary host-sets
    hosts              Manage Boundary hosts
    proxy              Launch the Boundary CLI in proxy mode
    roles              Manage Boundary roles
    scopes             Manage Boundary scopes
    server             Start a Boundary server
    sessions           Manage Boundary sessions
    targets            Manage Boundary targets
    users              Manage Boundary users
```

**Additional context**

Microsoft Windows Version 1909 (OS Build 18363.1256)

```
PS C:\> wsl -l -v
  NAME      STATE           VERSION
* Ubuntu    Running         2
```

```
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.1 LTS
Release:        20.04
Codename:       focal

$ uname -a
Linux mooncake 4.19.128-microsoft-standard #1 SMP Tue Jun 23 12:58:10 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

$ dpkg -l boundary
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name           Version      Architecture Description
+++-==============-============-============-====================================================================================================================================
ii  boundary       0.1.2        amd64        Boundary is a tool for identity-based secure access management. Please submit issues to https://github.com/hashicorp/boundary/issues
```

**Comment by frntn** [comment]
As the issue occured on a fresh install I had no real data on disk, so I decided to reinstall ubuntu 
```
PS C:\> wsl --unregister Ubuntu
Unregistering...
```

```
$ curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
$ sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
$ sudo apt-get update && sudo apt-get install boundary

$ boundary
Usage: boundary <command> [args]

Commands:
    accounts           Manage Boundary accounts
    auth-methods       Manage Boundary auth-methods
    auth-tokens        Manage Boundary auth-tokens
    authenticate       Authenticate the Boundary command-line client
    config             Manage resources related to Boundary's local configuration
    connect            Authorize a session against a target and launch a proxied connection
    database           Manage Boundary's database
    dev                Start a Boundary dev environment
    groups             Manage Boundary groups
    host-catalogs      Manage Boundary host-catalogs
    host-sets          Manage Boundary host-sets
    hosts              Manage Boundary hosts
    proxy              Launch the Boundary CLI in proxy mode
    roles              Manage Boundary roles
    scopes             Manage Boundary scopes
    server             Start a Boundary server
    sessions           Manage Boundary sessions
    targets            Manage Boundary targets
    users              Manage Boundary users
```

**Comment by frntn** [comment]
I have checked each available versions : 
```
$ apt-cache madison boundary
  boundary |      0.1.2 | https://apt.releases.hashicorp.com focal/main amd64 Packages
  boundary |      0.1.1 | https://apt.releases.hashicorp.com focal/main amd64 Packages
  boundary |    0.1.0-2 | https://apt.releases.hashicorp.com focal/main amd64 Packages
  boundary |      0.1.0 | https://apt.releases.hashicorp.com focal/main amd64 Packages
```

✔️ `boundary` only work for the following version : 

- `0.1.0`
- `0.1.0-2`

❌ `boundary` doesn't work since then : 

- `0.1.1`
- `0.1.2`

**Comment by jefferai** [comment]
This should have been fixed in 0.1.3. That has a bug affecting listeners, 0.1.4 will be out soon. If it's still affecting you, make sure you don't have BOUNDARY_KEYRING_TYPE set.

**Comment by frntn** [comment]
It is actually still affecting me in `0.1.3` : 

```
$ wget https://releases.hashicorp.com/boundary/0.1.3/boundary_0.1.3_linux_amd64.zip

$ unzip boundary_0.1.3_linux_amd64.zip

$ ./boundary
panic: runtime error: slice bounds out of range [308:282]

goroutine 1 [running]:
github.com/godbus/dbus.getSessionBusPlatformAddress(0x1818187, 0x18, 0x0, 0x0)
        /root/go/pkg/mod/github.com/godbus/dbus@v4.1.0+incompatible/conn_other.go:30 +0x295
github.com/godbus/dbus.getSessionBusAddress(0x0, 0x0, 0x0, 0x0)
        /root/go/pkg/mod/github.com/godbus/dbus@v4.1.0+incompatible/conn.go:96 +0xf8
github.com/godbus/dbus.SessionBusPrivate(0x0, 0x169bf40, 0x2660e60)
        /root/go/pkg/mod/github.com/godbus/dbus@v4.1.0+incompatible/conn.go:101 +0x25
github.com/godbus/dbus.SessionBus(0x0, 0x0, 0x0)
        /root/go/pkg/mod/github.com/godbus/dbus@v4.1.0+incompatible/conn.go:73 +0xb5
github.com/99designs/keyring.init.1()
        /root/go/pkg/mod/github.com/99designs/keyring@v1.1.6/kwallet.go:24 +0x51

$ env | grep BOUNDARY_KEYRING_TYPE
# ...no output...
```

**Comment by jefferai** [comment]
@frntn 0.1.4 will be out tomorrow; I've updated our deps which include some extra checks to help protect against this. Please test it when it's out and let me know if it's all fixed for you!

**Comment by jefferai** [comment]
@frntn 0.1.4 is out, can you test again?

**Comment by frntn** [comment]
Fixed ✔️  
Thanks @jefferai 👍

```
[10:12:10]
$ unzip boundary_0.1.4_linux_amd64.zip
Archive:  boundary_0.1.4_linux_amd64.zip
  inflating: boundary

[10:12:32]
$ ./boundary
Usage: boundary <command> [args]

Commands:
    accounts           Manage Boundary accounts
    auth-methods       Manage Boundary auth methods
    auth-tokens        Manage Boundary auth tokens
    authenticate       Authenticate the Boundary command-line client
    config             Manage resources related to Boundary's local configuration
    connect            Connect to a target through a Boundary worker
    database           Manage Boundary's database
    dev                Start a Boundary dev environment
    groups             Manage Boundary groups
    host-catalogs      Manage Boundary host catalogs
    host-sets          Manage Boundary host sets
    hosts              Manage Boundary hosts
    roles              Manage Boundary roles
    scopes             Manage Boundary scopes
    server             Start a Boundary server
    sessions           Manage Boundary sessions
    targets            Manage Boundary targets
    users              Manage Boundary users

[10:12:38]
$ ./boundary version

Version information:
  Git Revision:        f8577519b6fb152ddb19b2e4a7dcf8e9b1e82f58
  Version Number:      0.1.4
```
