### ISSUE TITLE
Nil reference with BOUNDARY_TLS_INSECURE

### ISSUE THREAD

**Issue by kmaris** [hashicorp/boundary#902]
**Describe the bug**
When attempting to `boundary authenticate password ...` with TLS verification disabled via BOUNDARY_TLS_INSECURE the client gets a seg fault.

**To Reproduce**
1. export BOUNDARY_ADDR='https://boundary.self-signed.service.com'
2. export BOUNDARY_TLS_INSECURE='true'
3. boundary authenticate password -auth-method-id=... -login-name ... -password ...

**Expected behavior**

```
$ boundary authenticate password ...

Authentication information:
  Account ID: ...
  Auth Method ID: ...
  Etc...
```

**Actual Behavior**

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0xa0 pc=0x88efbb]

goroutine 1 [running]:
github.com/hashicorp/boundary/api.(*Config).ConfigureTLS(0xc00049e180, 0xc0004864e0, 0x0)
        /go/api/client.go:199 +0x1db
github.com/hashicorp/boundary/api.(*Config).ReadEnvironment(0xc00049e180, 0xc000486480, 0x40e358)
        /go/api/client.go:349 +0x505
github.com/hashicorp/boundary/api.DefaultConfig(0xc00089fa98, 0x2, 0x2)
        /go/api/client.go:148 +0xf8
github.com/hashicorp/boundary/internal/cmd/base.(*Command).Client(0xc0002681a0, 0xc00089fa98, 0x2, 0x2, 0x0, 0x0, 0xc00089f940)
        /go/internal/cmd/base/base.go:125 +0x7a
github.com/hashicorp/boundary/internal/cmd/commands/authenticate.(*PasswordCommand).Run(0xc0005a8000, 0xc00003a0b0, 0x5, 0x5, 0xc0002e6420)
        /go/internal/cmd/commands/authenticate/password.go:117 +0x136
github.com/mitchellh/cli.(*CLI).Run(0xc000795a40, 0xc000795a40, 0xc0002e7ce0, 0xc0002e6380)
        /root/go/pkg/mod/github.com/mitchellh/cli@v1.1.2/cli.go:262 +0x1cf
github.com/hashicorp/boundary/internal/cmd.RunCustom(0xc00003a090, 0x7, 0x7, 0xc00089fe60, 0xc00004a0b8)
        /go/internal/cmd/main.go:186 +0x846
github.com/hashicorp/boundary/internal/cmd.Run(...)
        /go/internal/cmd/main.go:92
main.main()
        /go/cmd/boundary/main.go:13 +0xda
```

**Additional context**

Looks like go-cleanhttp is leaving the TLSClientConfig nil. I've submitted #901 as an example fix but I don't develop in Go so it might not be a good fix. You could also [make the client config not null here][1]?

After building the boundary binary with the above fix authentication succeeds.

[1]: https://github.com/hashicorp/go-cleanhttp/blob/d3fcbee8e1810ecee4bdbf415f42f84cfd0e3361/cleanhttp.go#L13

**Comment by jefferai** [comment]
901 merged, thanks!
